spring:
  application:
    name: spring-mvc
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    me.snowlight: debug
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace