spring:
  profiles:
    active: stress
---
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: spring-mvc
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    me.snowlight: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
---
spring:
  config:
    activate:
      on-profile: stress
  datasource:
    url: jdbc:mariadb://localhost:3306/sample # r2dbc:pool:mariadb://localhost:3306/sample
    username: user
    password: 1234